### ISSUE TITLE
1.18.2版本mc中烤地瓜mod无法正常运行

### ISSUE THREAD

**Issue by h15588** [teddyxlandlee/sweet_potato#31]
**Describe the bug**
创建新世界时提示当前选中的数据包中出现了错误，导致世界无法加载（即使我没有安装任何数据包与任何其他模组）
**To Reproduce**
仅安装1.18.2版本mc，fabric, fabric api,烤地瓜模组后试图创建新的世界
**Desktop (please complete the following information)**
os: Windows10
java: Azul Zulu: 17.34.19
mod: fabric-api-0.56.1+1.18.2.jar, sweet_potato_mod-1.4.4+1.18.2.jar
数据包:default,fabric mod
[latest.log](https://github.com/Featurehouse/sweet_potato-issueTracker/files/8988605/latest.log)

**Comment by teddyxlandlee** [comment]
Confirmed.

**Comment by teddyxlandlee** [comment]
Fixed in 1.4.18.
